import random
maps = ["TRIBAL 1","TRIBAL 2","TRIBAL SANDBOX","FARMER 1","FARMER 2","MEDIEVAL 1","MEDIEVAL 2","ANCIENT 1","ANCIENT 2","ANCIENT SANDBOX","VIKING","VIKING SANDBOX","DYNASTY","RENEISSANCE","PIRATE","SPOOKY 1","SPOOKY 2","WILD WEST","LEGACY","FANTASY GOOD","FANTASY EVIL","FARMER SNOW"]
rnumber = random.randrange(0, len(maps))
print(maps[rnumber])